# Generated by Django 3.0.5 on 2021-02-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='uploadDate',
            field=models.DateField(auto_now=True),
        ),
    ]
