# Generated by Django 3.0.5 on 2021-03-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_newsandupdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrationRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='newsandupdates',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
