# Generated by Django 3.0.5 on 2021-04-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_registrationrequest_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('deadline', models.DateField()),
                ('deadlineTime', models.TimeField()),
                ('assignmentFile', models.FileField(upload_to='')),
            ],
        ),
    ]
