# Generated by Django 3.0.5 on 2021-04-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.subject'),
            preserve_default=False,
        ),
    ]
