# Generated by Django 3.0.5 on 2021-04-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_assignments_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
